### ISSUE TITLE
The STEM software link on the homepage seems broken

### ISSUE THREAD

**Issue by lfaller** [jernst98/STEM_DREM#2]
I keep getting a Network failure mode when I try.

How should I compile the java code in the github directory?

Thanks for any advice!

**Comment by jernst98** [comment]
The STEM website is accessible for me.
Can you access the STEM website through this alternative URL instead
https://www.cs.cmu.edu/~jernst/stem/
?

-Jason

**Comment by lfaller** [comment]
Yes I can access the webpage, but once I click the download link it doesn't actually download the file, it just reports the "Network failure" message. Can you confirm that the download link is working?

Thanks!

**Comment by jernst98** [comment]
I confirmed the download link worked for me both from a laptop wifi and a
smart phone cellular network.
Can you try from a different network?

-Jason

**Comment by lfaller** [comment]
I tried from both a wireless and a wired connection, and in both cases the file seems to download almost completely but never makes it entirely.

![screen shot 2017-06-01 at 1 57 04 pm](https://cloud.githubusercontent.com/assets/7854149/26693484/52ea8ed2-46d2-11e7-9fb3-4cc0e9351b2e.png)

**Comment by jernst98** [comment]
Are you seeing this error from multiple different browsers?

Are the wireless and wired connection to the same network?
Have you seen this connecting from a different network?

-Jason

**Comment by lfaller** [comment]
Both the wired and wireless connection are part of the same network. I have not been able to try from a different network.

**Comment by jernst98** [comment]
Do you see it from different browsers on the network you are using?

-Jason

**Comment by lfaller** [comment]
Yes. I first tried with Chrome, and it is also not working with Safari.

This is on a Mac 10.11.6

Chrome: Version 57.0.2987.133 (64-bit)
Safari: Version 10.0.1 (11602.2.14.0.7)

![screen shot 2017-06-02 at 12 29 52 pm](https://cloud.githubusercontent.com/assets/7854149/26735291/49f8ac74-478f-11e7-8778-f319787d066f.png)

**Comment by jernst98** [comment]
If you send a direct email to me, I can try emailing you the zip file.

-Jason
