### ISSUE TITLE
some questions about the  algorithm of STEM

### ISSUE THREAD

**Issue by fengqing-dong** [jernst98/STEM_DREM#3]
hi，
when I read the paper , which introduce the algorithm of STEM, there were some questions   hard to understand.
> The paper : Clustering short time series gene expression data.
> doi:10.1093/bioinformatics/bti1022
1. How to calculate the value of d(p1, p2)?
The distance between any two profiles was introduced in the chapter **2.1 Selecting model profiles**, but  the algorithm of  calculating it seem not to be described. could you tell me which mothod/algorithm was used to fix it? 

2. How to calculate `$ s^j_i $`or `$ S_i $`?
> Let `$ s^j_i $` be the number of genes assigned to model profile i in permutation j (j is one of the n! possible permutations). 

the  `$ s^j_i $`or `$ S_i $` is important to for calculating P (X ≥ t(mi)), whereX ∼ Bin(|G|, Ei/|G|).
This sentence is confusing to me . could you give some example to interpret it?

**Comment by jernst98** [comment]
1. See section 2.3 of the manuscript on the distance function

2. A permutation $j$ is a reordering of the time points (columns of the data). For the permutation, each gene is assigned to the profile from which it has the smallest distance. $s^j_i$ is the number of genes assigned to profile $i$ under permutation $j$.
