### ISSUE TITLE
Can DREAM be applied into ATAC and RNA pair data to get TF network?

### ISSUE THREAD

**Issue by shangguandong1996** [jernst98/STEM_DREM#5]
Hi, Dear developer
I found user can enter the **Time Specific Binding Data** to DREAM. But it always the time-specifc **ChIP-Seq data** , which means you just only input some limit TF.
I am wondering If I have the time-series **ATAC-Seq** data, which I can predict hundreds of TF binding site from. It can also get **Time Specific Binding Data**.
I am wondering whether it can produce more powerful results or more noise ?

**Comment by jernst98** [comment]
TF-binding predictions for DREM do not have to come from ChIP-seq and using other strategies such ATAC-seq+motifs is also an option. ATAC-seq+motifs allow you predict binding for more TFs, while ChIP-seq allows a more confident set of predictions for fewer TFs, but the exact tradeoffs will likely be specific to your data and system.

**Comment by shangguandong1996** [comment]
Thanks :)
