### ISSUE TITLE
Whether the Model Profiles Overview Interface can be exported as a vector graph

### ISSUE THREAD

**Issue by shaos1996** [jernst98/STEM_DREM#6]

**Comment by jernst98** [comment]
No. You need to use print screen.

**Comment by jernst98** [comment]
A correction to above. As of version 1.3.8 the main interface can be saved to svg format by giving a .svg extension after clicking the disk icon on  the main interface screen. Sorry for the confusion.

**Comment by shaos1996** [comment]
﻿
Many thanks！
