### ISSUE TITLE
Some questions about DREM

### ISSUE THREAD

**Issue by oyshilin** [jernst98/STEM_DREM#7]
Recently I have studied how to analyze the time-series RNA-Seq and read some articles. Some articles used DREM to find the signaling pathways or construct the signaling network, which prompts me to download DREM and try to use it. After reading the manual book and several analysis, I have some questions while using it.
 1. When I input the expression data file, which kind of DEGs should I input, the DEGs express at any time points or at each time points?
 2. What dose 0 or 1 mean? Do they represent the logical number?
 3. In the Key TFs Label of output inter face, I am still confused about path significance conditional on split, path significance overall and split significance. And when I click these three different buttons, there are some odd phenomena.(pictures are below, the first one is path significance conditional on spot and the second is path significance overall ) I am wondering which result is more reliable?
 Thank you very much for your kind consideration and I am looking forward to your early reply.
![path significance conditional on split](https://user-images.githubusercontent.com/69614511/144868909-44364e81-ddf0-4ad6-b0b5-4f1b915bc6d1.png)
![path significance overall](https://user-images.githubusercontent.com/69614511/144868925-33e8bc37-9e7f-4a63-a024-49618c6f72e2.png)

**Comment by jernst98** [comment]
1. Being differentially expressed at any time point would make more sense than requiring all time points

2. A '1' means the TF is predicted to regulate the gene based on the TF-gene input, and '0' others

3. Path significance conditional on split is more localized than path significance. It says among the genes that went into the split there is an enrichment of targets of the TF on the labeled path. Path significance overall takes into account both the gene filtering if done within DREM and the series of splits leading to the specific path. Split significance is relevant if you are inputting activators and repressors separately (encoded as '1' and '-1'), and identifies splits for which genes that are predicted to be activated take one path and those that are repressed take a different path on average in the case of two way splits and with generalizations in the case of multi-way splits.

**Comment by oyshilin** [comment]
Thanks for your reply, Dr. Ernst.
I have another question. When I am using DREM，I have two date sets for input, one with Spot IDs and the other without Spot IDs, and the results shows some differences, e.g. there are different paths in the results. So I'm curious about the function of Spot IDs in the data set and also wonder whether the Spot IDs make differences for the result or not.

**Comment by jernst98** [comment]
Are the files and options exactly the same except for the inclusion of the Spot IDs and are you checking 'Spot IDs in the data file'?
I don't think the inclusion of Spot IDs should lead to different results, but if they are I will need to look into why.
The point of Spot IDs was to allow DREM to handle gene expression input data files where there was multiple measurements for the same gene. These would be merged before DREM does its modeling.

**Comment by oyshilin** [comment]
> Are the files and options exactly the same except for the inclusion of the Spot IDs and are you checking 'Spot IDs in the data file'? I don't think the inclusion of Spot IDs should lead to different results, but if they are I will need to look into why. The point of Spot IDs was to allow DREM to handle gene expression input data files where there was multiple measurements for the same gene. These would be merged before DREM does its modeling.

Thank you for your replying and I found the reason why the result is different-it is just a small mistake when I input the data to the DREM. And I'm curious that if I want to find the TFs of the green splits, which step should I choose,  the split table or the Key TFs labels?

**Comment by jernst98** [comment]
They should provide the same information if you choose the 'Split Significance' option under Key TFs labels except the table will provide more details. If you are interested in a specific path out of the split, that you can also get under the appropriate option  from Key TFs with more details by right clicking on the path.

**Comment by oyshilin** [comment]
> They should provide the same information if you choose the 'Split Significance' option under Key TFs labels except the table will provide more details. If you are interested in a specific path out of the split, that you can also get under the appropriate option from Key TFs with more details by right clicking on the path.

After I right clicking the specific path out of the split points, there is a column called Num Path in the path table. According to the manual, this column is the number of the genes going through the node. I wonder if the Num path is bigger than 0, the TF in the same row will be the TFs of the green split points?

**Comment by jernst98** [comment]
It is the number of genes on that path. Just having Num Path bigger than 0 alone is not sufficient for the TF to appear labeled on the split point on the interface.
