### ISSUE TITLE
Does the 1st column have to include gene symbols?

### ISSUE THREAD

**Issue by Dmorgen** [jernst98/STEM_DREM#8]
can I use Uniprot? or peptide sequence (for peptidomics data)?

Thanks!
D.

**Comment by jernst98** [comment]
No, it doesn't, but if you are using symbols not found in the annotation files you won't be able to do the GO enrichments.

**Comment by Dmorgen** [comment]
That’s ok – I just want to determine which peptide have what trends, that’s all. If it can accept peptide sequences with modification, that’d be great! Would square brackets with numbers in them and letters be ok?

Thanks!
David.

**Comment by jernst98** [comment]
Yes, I think that should work.

**Comment by Dmorgen** [comment]
Thanks!
D.
