### ISSUE TITLE
Getting coordinates of DREM nodes

### ISSUE THREAD

**Issue by eschiks** [jernst98/STEM_DREM#9]
Hello, I'm wondering if there is a way to get the y coordinates of the DREM nodes so I can re-make the plot of the paths on my own?

**Comment by jernst98** [comment]
They are written in the model file. They are on the lines with three numbers. The first number is a node mean, the second is the standard deviation, and the third is how many paths out of the node there are. The nodes are arranged in a depth first manner (i.e. it follows one path to the end, then from the last branch point, and so forth). 

Also, if you mouse over a node on the interface you can also get the mean and standard deviation values for individual nodes.

**Comment by eschiks** [comment]
This is very helpful, thanks!
